/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPut;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.message.BasicNameValuePair;

/**
 *
 * @author noobf
 */
public class PnUserInfo extends javax.swing.JPanel {
    String workingDir = System.getProperty("user.dir");
    File info = new File(workingDir + "/temp/userInfo.txt");
    /**
     * Creates new form PnUserInfo
     */
    public PnUserInfo() {
        initComponents();
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        pwNewPW.setVisible(false);
        pwReEnter.setVisible(false);
        btConfirm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        btChangePW = new javax.swing.JButton();
        btConfirm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pwNewPW = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        pwReEnter = new javax.swing.JPasswordField();
        btDisplay = new javax.swing.JButton();
        btBack = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin người dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("ID Hệ thống:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Tên người dùng:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        lbID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btChangePW.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btChangePW.setText("Đổi mật khẩu");
        btChangePW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btChangePWMouseClicked(evt);
            }
        });

        btConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btConfirm.setText("Xác nhận");
        btConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConfirmMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Mật khẩu mới:");

        pwNewPW.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Nhập lại mật khẩu mới:");

        pwReEnter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btDisplay.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btDisplay.setText("Hiển thị");
        btDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDisplayMouseClicked(evt);
            }
        });

        btBack.setText("<html>Back ↵");
        btBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btChangePW)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(105, 105, 105))
                                            .addComponent(pwNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pwReEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDisplay)
                    .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btChangePW))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pwNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwReEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addComponent(btConfirm)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void readFile() throws FileNotFoundException, IOException{
        BufferedReader br = new BufferedReader(new FileReader(info));   
        String st = "";  
        st = br.readLine();
        String[] arr = st.split("/");
        lbID.setText(arr[0]);
        lbName.setText(arr[1]);
    }
    private void btDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDisplayMouseClicked
        try {
            // TODO add your handling code here:
            readFile();
        } catch (IOException ex) {
            Logger.getLogger(PnUserInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDisplayMouseClicked

    private void btChangePWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btChangePWMouseClicked
        // TODO add your handling code here:
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        pwNewPW.setVisible(true);
        pwReEnter.setVisible(true);
        btConfirm.setVisible(true);
    }//GEN-LAST:event_btChangePWMouseClicked
    private JPanel pnUserInfo;
    /**
     * Xác định panel sẽ hiển thị khi muốn xem thông tin chi tiết của 1 sinh viên
     * @param pnUserInfo
     */
    public void PnBacktoMain(JPanel pnUserInfo){
        this.pnUserInfo = pnUserInfo;
    }; 
    private void btBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBackMouseClicked
        JFrame parent = Utitilities.findJFrameOf(this);
        if (parent != null) {
            parent.setContentPane(pnUserInfo);
            parent.pack();
        } else {
            JOptionPane.showMessageDialog(parent, "Panel Login only used for JFrame");
            System.exit(1);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btBackMouseClicked
    
    private void sendPut() throws UnsupportedEncodingException, MalformedURLException, IOException{
        int select = JOptionPane.showConfirmDialog(null, "Xác nhận đổi mật khẩu?",
                "Chú ý", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(select == JOptionPane.NO_OPTION){
            return;
        }else{
            String id = lbID.getText();
            id = URLEncoder.encode(id, "UTF-8");
            HttpClient httpclient = new DefaultHttpClient();
            HttpPut httpput = new HttpPut("http://localhost:3000/users/changePassword/" + id);
            String newPW = new String(pwNewPW.getPassword());
            List <NameValuePair> nvps = new ArrayList <NameValuePair>();
            nvps.add(new BasicNameValuePair("newPW", newPW));
            try{
                httpput.setHeader("Accept", "application/x-www-form-urlencoded");
                httpput.setHeader("Content-Type", "application/x-www-form-urlencoded");
                httpput.setEntity(new UrlEncodedFormEntity(nvps, "UTF-8"));
                System.out.println("Requesting : " + httpput.getRequestLine());
                HttpResponse response = httpclient.execute(httpput);
                int responseCode = response.getStatusLine().getStatusCode();
                String responseBody = response.getStatusLine().getReasonPhrase();
                if(responseCode == 200){
                    JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công!",
                            "Success", JOptionPane.INFORMATION_MESSAGE);
                }else {
                    JOptionPane.showMessageDialog(null, "Lỗi!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                System.out.println("Response code:" +  responseCode + "/nResponseBody:" + responseBody);
            }catch(ClientProtocolException e){
                JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.INFORMATION_MESSAGE);
            }finally{
                httpclient.getConnectionManager().shutdown();
            }
        }
    }
    
    private void btConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmMouseClicked
        // TODO add your handling code here:
        if(pwNewPW.getPassword().length == 0 || pwReEnter.getPassword().length == 0){
            JOptionPane.showMessageDialog(null, "Nhập thiếu thông tin", "Đổi mật khẩu lỗi!", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(!Arrays.equals(pwNewPW.getPassword(), pwReEnter.getPassword())){
            JOptionPane.showMessageDialog(null, "Nhập lại mật khẩu không đúng", "Đổi mật khẩu lỗi!", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            try {
                sendPut();
            } catch (MalformedURLException ex) {
                Logger.getLogger(PnUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PnUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btConfirmMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btChangePW;
    private javax.swing.JButton btConfirm;
    private javax.swing.JButton btDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JPasswordField pwNewPW;
    private javax.swing.JPasswordField pwReEnter;
    // End of variables declaration//GEN-END:variables
}
